### ISSUE TITLE
Automate Talawa-Docs updates from All Talawa Repos

### ISSUE THREAD

**Issue by palisadoes** [PalisadoesFoundation/talawa-docs#191]
The technical documentation across all Talawa projects needs to be greatly improved. One way of achieving this goal is to find ways of adding documentation into the files of each code base in such a way that an external website such as that created by the Talawa-Docs repo is automatically updated. We foresee that this will require PR CI/CD integration Talawa-Docs between Talawa, Talawa-API and Talawa-Admin.

Using  [JSDoc](https://www.youtube.com/watch?v=Nqv6UkTROak)  (for the Talawa API and Admin Panel) and [dartdoc](https://pub.dev/packages/dartdoc) (for the Flutter App), enables us to generate documentation (in the form of static HTML files) from comments within the files, which can then be hosted on the site used for documentation. This will enable the documentation to grow organically with the codebase. To enforce this, a script would have to be made that checks if the comments are of the required form to generate the required HTML file. This script would be triggered by a Github action when a new pull request occurs. If the checks pass and the pull request is successful then this HTML file (artifact) would be sent to the docs repo and overwrite any previous version of that HTML file. Once added to the repo, styling would be added to the file so that it is inline with the aethestic of the documentation site (again this would be done with a script that gets triggered from a Github action).

## We will not be assigning this issue to contributors, only the issues below.

**Summary**

- We need a semi/fully automated method of updating our documentation as the codebase changes overtime. The main orchestrator of things will be our CI/CD pipeline through use of a couple actions for ease of management and accountability. 
- Additionally, we will need to update the CONTRIBUTORS.md and CODE_OF_CONDUCT.md files in each repository to require users to make updates to the documentation where necessary. 

**Proposed GitHub Action**

The person assigned this issue should consider these factors:

- Reference Video: https://www.youtube.com/watch?v=-lI1LjhB_FE

The proposed Github Actions - CI/CD sequence of actions are as follows:

```
- Action 1 (Talawa API)
    - Pulls API
    - Generates Docs (/docs)
    - Commit
    - Trigger

- Action 2 (Talawa API)
    - Checks for comments and their validity
        - Fails if Invalid

- Action 3 (Talawa Mobile)
    - Pulls Mobile
    - Generates Docs (/docs)
    - Commit

- Action 4 (Talawa Mobile)
    - Checks for comments and their validity
        - Fails if Invalid

-  Action5 (Talawa Docs): Webhook Trigger for document repository
    - Copy Docs from external Repos
    - Apply HTML Mods (If Necessary)
    - Commit
```

**Technologies Explored**

These technologies should be explored as part of the solution:

- `Talawa-API` and `Talawa-Admin`
    - Swagger UI/JS Docs - Javascript comments for API Documentation (Semi-Automated)
          - https://www.youtube.com/watch?v=S8kmHtQeflo
    - Customisability
          - https://mrin9.github.io/RapiDoc/
          - https://redoc.ly/pricing/
    - SpectaQL - GraphQL Documentation (Automated)
          - Current Implementation (Needs to be tied to a Github Action)
          - https://github.com/TheHazeEffect/talawa-api/tree/master

- `Talawa Mobile`
    - DartDocs
    - JSDocs equivalent for Dart

This is a parent issue for these issues:

- **Auto Generate Talawa Documentation in Each Repo**
    - https://github.com/PalisadoesFoundation/talawa-docs/issues/188
    - https://github.com/PalisadoesFoundation/talawa-docs/issues/189
    - https://github.com/PalisadoesFoundation/talawa-docs/issues/190
- **Format the Repo Documentation Like the [Talawa Documentation Website](https://palisadoesfoundation.github.io/talawa-docs/)**
    - https://github.com/PalisadoesFoundation/talawa-docs/issues/199
    - https://github.com/PalisadoesFoundation/talawa-docs/issues/200

**Comment by DMills27** [comment]
We can go about this using the following approach:

Using  [JSDoc](https://www.youtube.com/watch?v=Nqv6UkTROak)  (for the Talawa API and Admin Panel) and [dartdoc](https://pub.dev/packages/dartdoc) (for the Flutter App), enables us to generate documentation (in the form of static HTML files) from comments within the files, which can then be hosted on the site used for documentation. This will enable the documentation to grow organically with the codebase. To enforce this, a script would have to be made that checks if the comments are of the required form to generate the required HTML file. This script would be triggered by a Github action when a new pull request occurs. If the checks pass and the pull request is successful then this HTML file (artifact) would be sent to the docs repo and overwrite any previous version of that HTML file. Once added to the repo, styling would be added to the file so that it is inline with the aethestic of the documentation site (again this would be done with a script that gets triggered from a Github action).


This approach is encapsulated in the following issues:

-
-
-

**Comment by adepeju4** [comment]
hiii can i work on this?

**Comment by palisadoes** [comment]
Thanks. It's already assigned. It's a work in progress

**Comment by KASHISH17RAMANI** [comment]
please allow me to contribute to this issue

**Comment by suhana832** [comment]
can you assign this task to me?
