### ISSUE TITLE
Feature Request:- Talawa doc overview section needs to be rewritten

### ISSUE THREAD

**Issue by Biki-das** [PalisadoesFoundation/talawa-docs#390]
**Is your feature request related to a problem? Please describe.**
The current overview section of the talawa docs need some more content , as it just now exist as a one liner, describing the important key features and objective of the talawa project would be suitable here. This would result in a more brief overview.

![Overview _ Talawa Project Documentation — Mozilla Firefox 3_9_2023 9_34_35 AM](https://user-images.githubusercontent.com/72331432/223914235-13270a11-f560-4d19-a5a3-3362bac03bb4.png)

**Describe the solution you'd like**
Adding more content to give a more clear overview of the Talawa Project

**Approach to be followed (optional)**
I would research more and try to come up with a more detailed overview.

**Additional context**

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by RotimiDesire** [comment]
**Status quo of the documentation overview:**
The current doc overview only gives a brief, one line description of what Talawa is about without necessarily going into other important details.

**My idea of what a rewritten documentation overview should like:**
The documentation overview should provide a clear, comprehensive and detailed synopsis of the website's importance, features and purpose. This is aimed at explaining to users what Talawa is set out to achieve while also including specific demographics and characteristics that are relevant.
There should also be an overview of the website's functionality entailing the features and tools that are made accessible to users as well as the website's possible navigation systems.


I strongly believe that a lot more than I have mentioned above could be implemented into the documentation overview and this can be made possible with further research alongside in-depth knowledge about Talawa herself.

**Comment by RotimiDesire** [comment]
I'd love to be assigned to this issue.

**Comment by Biki-das** [comment]
Sure @RotimiDesire we can collab on this issue!

**Comment by Yass32** [comment]
Hello @Biki-das can we collaborate on this

**Comment by RotimiDesire** [comment]
Sure, that would be great. @Biki-das

**Comment by palisadoes** [comment]
1. There seems to be confusion in the Outreachy community about Talawa. We interchangeably use Talawa to mean all three projects and the mobile app. This will need to change
1. This page is specific for technical resources for the mobile app users. 
1. As this is a technical page, if you have technical content for that which is not in the existing markdown files in the main talawa repository then consider adding it, otherwise it should stay blank.
1. At a minimum, this page should be titled Talawa Mobile.

Only one issue per person as outlined in our CONTRIBUTING.md file.  If the currently assigned person, or a mentor feels that it is a big enough issue to be split, then that could be done. This is very important if you are planning on applying for an internship. With shared issues, it is difficult to know the level of contribution of each person.

@Cioppolo14 take note of these comments when reviewing the PR

**Comment by iamatifmoin** [comment]
@palisadoes 
I'd like to work on this since nobody is currently assigned.

**Comment by suhana832** [comment]
can you assign this task to me ?

**Comment by palisadoes** [comment]
Unassigning due to inactivity and no submitted PR. Others need to get a chance. Please let us know whether you want to be reassigned before someone else requests assignment or select another issue.

Closing till we know what content should be there.

**Comment by salman-farooqi** [comment]
I would like to work on this issue, will go through all the discussion above, and will come up with the content for Overview section. And, will also change the name 'Talawa' to 'Talawa Mobile'.
Thank you!
@palisadoes
