### ISSUE TITLE
Installation of docusaurus using npm specific information does not work.

### ISSUE THREAD

**Issue by Collette-vershalli** [PalisadoesFoundation/talawa-docs#431]
**Describe the bug**

Following the instructions in the documentation for installing docusaurus using npm returns an error message.

**To Reproduce**

1.git clone https://github.com/PalisadoesFoundation/talawa-docs
2. cd talawa-docs
3. npm install docusaurus

**Expected behavior**
These steps should lead to a successful  installation of docusaurus.

**Actual behavior**
Displays an error message each time the last command is run.

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by Collette-vershalli** [comment]
To fix this issue i would like to remove the npm specific information, since they do not carry out the required task allowing just the yarn specific information.
i would like to work on this issue if allowed @palisadoes, @xoldyckk

**Comment by Collette-vershalli** [comment]
This issue has been resolved already by someone else

**Comment by xoldd** [comment]
@Collette-vershalli You have to remove npm related information. Only yarn v1 related information must be there.

**Comment by Collette-vershalli** [comment]
Thank you @xoldyckk . Some of the npm related information work, like for instance npm run start for starting the development server. should i  remove that too?

**Comment by xoldd** [comment]
@Collette-vershalli Currently there's too much extra information. Take a look at talawa-api's docs and nodejs installation section. That's all the information we need to give for someone to install npm and nodejs. The contributers have to figure out themselves how to install all this stuff on their respective operating systems.

Since talawa-docs makes use of yarn instead of npm, just that information needs to be included here. So, you remove all that npm related crap from docs, and only mention how to install nodejs(copy the installation instructions from talawa-api), and then proceed to explain how to install yarn v1(use [this](https://classic.yarnpkg.com/en/docs/install) link). Also, mention that talawa-docs only works with yarn v1. After that you can also mention how to run talawa docs using yarn for development.

**Comment by Collette-vershalli** [comment]
ok thank you understood :)

**Comment by palisadoes** [comment]
@Collette-vershalli Be aware of this issue. Please coordinate with @Vic-Orlands so that your PR is merged first.

- https://github.com/PalisadoesFoundation/talawa-docs/issues/419

**Comment by palisadoes** [comment]
@Collette-vershalli The information that we have for the various operating systems should remain, but be substantially trimmed. It will be sufficient to have a link to the installation guides for each OS. Though it may seem straight forward to experienced IT people, Talawa-Docs will be mostly used by technical writers  with less knowledge.

**Comment by Collette-vershalli** [comment]
Alright thank you I'll get to them immediately.

**Comment by Vic-Orlands** [comment]
@Collette-vershalli I am working on the installation.md file. Let me know when you are done with this issue. This is so that I can add it to the installation file before making a PR.

**Comment by Collette-vershalli** [comment]
@Vic-Orlands  alright  i will

**Comment by Vic-Orlands** [comment]
@palisadoes @xoldyckk I want to take up this task. I spoke with @Collette-vershalli and she made it known that she has dropped out of the Outreachy program. Since it is related to my task, I want to work on this and get it merged first before making a PR on [this](#419) task

**Comment by xoldd** [comment]
@Vic-Orlands there you go

**Comment by Vic-Orlands** [comment]
> @Vic-Orlands there you go

Thank you. I just raised a PR for it.
