### ISSUE TITLE
Feature Request:- Adding Vale linter to the documentation repository

### ISSUE THREAD

**Issue by Biki-das** [PalisadoesFoundation/talawa-docs#467]
**Is your feature request related to a problem? Please describe.**
Since we have been finding a solution to automate and catch for style error and grammer, I have been experimenting with a tool called Vale (https://vale.sh/docs/vale-cli/overview/) , its a very popular and most importantly its unopinionated, it can scan multiple files at once or can traverse through a bunch of files at once. We can set our own styling rules along with the default ones, it has also a VOCAB folder where we can define word which we want to not count as errors and warning ,i have already added the talawa word there.

This would immediately add huge benefits for the Project both in terms of how well our documentation is, and the amount of time we are spending to make our docs better.

**Describe the solution you'd like**
The solution starts with a simple config file callled as `vale.ini` in the root of the repository, to make this tool work , once should have the vale cli installed locally in their machine and as for any other popular software it is available for mac, windows and linux (https://vale.sh/docs/vale-cli/installation/)
Below i demonstrated how this works.

https://user-images.githubusercontent.com/72331432/224535815-a03693df-b22d-4291-9abb-fd0bf9816a60.mp4

if implemented , we need to document this tool efficiently in our docs to help contributors and maintainers take the advantage of this tool.
I am also thinking of stretching the goal of this one , by setting up a GIthub action (https://github.com/marketplace/actions/vale-linter)
which will trigger the lint for every PR created for the docs!

Looking forward to the feedback of the maintainers , I feel this can add some good value to the Project

**Approach to be followed (optional)**
Adding a vale.ini config file
setting up the Vale CLI locally
Setting up the Vocab folder

For github workflows, more discussion will be required!

**Additional context**

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by Biki-das** [comment]
@Cioppolo14 @palisadoes  could you give me a feedback on this one?

**Comment by Biki-das** [comment]
@palisadoes could you give me some feedback on this!

**Comment by palisadoes** [comment]
Will not fix. This means that we will now have to support people's IDEs such as Visual Studio. 
That is why we have the `.vscode`  Visual Studio configuration directory added to the `.gitignore`  in all our repositories. If we didn't do that then every PR would upload people's personal settings. Every `git pull` would overwrite your settings with those of someone else.

Please take more time to think of your suggestions. They consume too much time for our reviewers.

Closing

**Comment by Biki-das** [comment]
> Will not fix. This means that we will now have to support people's IDEs such as Visual Studio. That is why we have the `.vscode` Visual Studio configuration directory added to the `.gitignore` in all our repositories. If we didn't do that then every PR would upload people's personal settings. Every `git pull` would overwrite your settings with those of someone else. 
> 
> Please take more time to think of your suggestions. They consume too much time for our reviewers.
> 
> Closing

not true @palisadoes you can use any choice of your ide, the only mandatory thing is vale being installed in the local machine 
which is available for all operating system [macos,windows and linux]. The Vale config has nothing to do with IDE, it is just an external config.

**Comment by palisadoes** [comment]
Thanks for the clarification. I assumed that we would be managing IDE settings because your screenshot was for VSCode hot the final product. I didn't realize that it was a video. Even so my concerns still stand.

People are not going to want to do this using the CLI. It is much more convenient to run this with in the IDE as this video shows:
- https://www.youtube.com/watch?v=VyVym_4gfGw

If we were to use it how would you propose we do so:
1. Without having to manage everyone's Visual Studio settings?
2. By standardizing the settings so that they are consistently applied?

**Comment by Biki-das** [comment]
i respect your view on this issue @palisadoes 
However I am still not able to understand your view of time consuming? a  issue has to be thoroughly discussed, between me and the maintainers, have i been able to explain the issue, is there any misalignment of explanation from myside, like this issue , there is a lot going on here, before coming to the conclusion of closing this, you did not asked the details whether this config is ide biased or anyone can use it without any config, i think this is not a healthy way of feeback , some issue require time and i understand i have been creating issues of the same nature from few days, and i again apologize for the same ,  and i am trying to create issue which have the potential to be worked on but i feel we need to have a few conversation to sort this out.
I again duly respect and appreciate the opinion of all mentors and maintainers!

**Comment by Biki-das** [comment]
@palisadoes sure i understand its just not about adding a tool to our product, it should be inclusive and easy to work with, let me do my research on the above points you mentioned and come up with a holistic approach.

**Comment by palisadoes** [comment]
I want to ensure you have a cogent argument before reopening. There has been a history of one line pull requests without much thought. I have mentioned this more than once and its impact on the limited time of our volunteers.

I want to emphasize the need for you to do the research first and consider the implications for a GitHub project with 100 forks. 

I am not keeping it closed out of disrespect. It is because I want you to be successful and it seems to be the only way to get your attention to change your behavior to one that benefits us all. For us to have a productive and cohesive community we must be considerate of the affected stakeholders.

If you are planning on applying for Outreachy, there is a need for high quality contributions to improve your evaluation as has been stated publicly in at least these two links.

1. https://docs.talawa.io/docs/internships/internship-selection-criteria
2. https://youtu.be/ThLeejU9CdE

Our desire to have higher quality PRs is a stated goal in our pull request guidelines: https://github.com/PalisadoesFoundation/talawa-docs/blob/develop/PR_GUIDELINES.md This applies to all contributors.

Your previous comment, which has now been deleted and the rationale for this response, was unjustified.

Please take the time to do the research so that you can successfully defend your case.

**Comment by Biki-das** [comment]
> I want to ensure you have a cogent argument before reopening. There has been a history of one line pull requests without much thought. I have mentioned this more than once and its impact on the limited time of our volunteers.
> 
> I want to emphasize the need for you to do the research first and consider the implications for a GitHub project with 100 forks.
> 
> I am not keeping it closed out of disrespect. It is because I want you to be successful and it seems to be the only way to get your attention to change your behavior to one that benefits us all. For us to have a productive and cohesive community we must be considerate of the affected stakeholders.
> 
> If you are planning on applying for Outreachy, there is a need for high quality contributions to improve your evaluation as has been stated publicly in at least these two links.
> 
>     1. https://docs.talawa.io/docs/internships/internship-selection-criteria
> 
>     2. https://youtu.be/ThLeejU9CdE
> 
> 
> Our desire to have higher quality PRs is a stated goal in our pull request guidelines: https://github.com/PalisadoesFoundation/talawa-docs/blob/develop/PR_GUIDELINES.md This applies to all contributors.
> 
> Your previous comment, which has now been deleted and the rationale for this response, was unjustified.
> 
> Please take the time to do the research so that you can successfully defend your case.

@palisadoes I understand and i felt later how this is affecting our work, again I am trying to do some valuable contributions, and the past activity won't be repeated in future . Looking forward to work further with you and the community.

futher should i work on this issue? i am digging on this one currently , if you prefer not to continue, we can stop and look for other issues to solve.

**Comment by palisadoes** [comment]
Yes
