### ISSUE TITLE
Add policy page on Talawa-API GraphQL error messaging

### ISSUE THREAD

**Issue by palisadoes** [PalisadoesFoundation/talawa-docs#567]
**Is your feature request related to a problem? Please describe.**
We need to add a page under the Talawa-API developers section on how we report GraphQL related errors. The conversation here needs to be converted into a Talawa-API policy.

- https://github.com/PalisadoesFoundation/talawa-api/discussions/1214

**Describe the solution you'd like**
See above

**Describe alternatives you've considered**

None

**Approach to be followed (optional)**
See above

**Additional context**
N/A

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by palisadoes** [comment]
@kb-0311 @xoldyckk Please take a look. We need to codify your thoughts here as part of our best practices

**Comment by kb-0311** [comment]
@palisadoes Sure but actually @xoldyckk has not given his thoughts regarding my recent comment on the thread where I cleared up his doubt regarding the sending of partial data with errors using my approach.

This will definitely require good documentation no doubt about that. My GSoC project will also cover the documentation of my approach to error handling too so don't panic about unclear undocumented changes.

Do you want documentation first then implementation or documentation during implementation?

**Comment by palisadoes** [comment]
Ask @xoldyckk for his final thoughts. 

I created a design guide page that we can use as a starting point. 

- https://github.com/PalisadoesFoundation/talawa-docs/blob/develop/docs/developers/talawa-api/design-guide.md

**Comment by kb-0311** [comment]
@palisadoes 
https://github.com/PalisadoesFoundation/talawa-api/discussions/1214#discussioncomment-5429967
Here that thread has been concluded. Should I start writing the documentation for the approach before it is implemented in GSoC?

**Comment by palisadoes** [comment]
1. Would this be a desired design philosophy for us to pursue independent of GSoC?
1. Is there a way to eventually automatically enforce it, even partially?

**Comment by kb-0311** [comment]
@palisadoes 
1. Yes this would be a desired error design philosophy for the talawa development community to pursue as a whole going forward. It is the best design approach when it comes to graphql and talawa API as Adarsh and I discussed and will give a lot of power to the Client apps and UI behavior in client apps, not just the API. But it would have to be implemented within the GSoC time period because it will change a lot of things so I will require to be focused on that aspect for a dedicated time in my GSoC period, the time I have already mentioned in my schedule section of proposal.
2. I actually am not sure what you mean could you elaborate? If you are asking if the design is backed up with type safety and consistency then yes, it can be enforced.

**Comment by palisadoes** [comment]
1. We just need to document it as a goal here. Our ideal state.
1. The implementation is a separate issue. The intent is not to implement it immediately, but to document it.
1. If we implement this approach, would there be a way to test the code submitted in each PR to make sure it's enforced?

**Comment by kb-0311** [comment]
@palisadoes 
 Alright, I will definitely write up the documentation for it in a few days.

If we implement it the unit tests will be a lot more consistent and accurate than they are right now since we will get rid of the mocks and handle errors directly from what the resolver is sending back.

My first priority for coming up with that approach was standard consistency and type safety which means the unit tests for the resolvers will be a lot more accurate than they are now. So yes the code base will be a lot more reliable and the tests will be enforced.

**Comment by palisadoes** [comment]
What's the status on this? Has the discussion on this in the API PR been resolved?

**Comment by kb-0311** [comment]
@palisadoes yeah the newer approach has been resolved by @xoldyckk in a separate thread.

https://github.com/PalisadoesFoundation/talawa-api/discussions/1239#discussioncomment-5492792

@xoldyckk Would you like to add anything else to the basic introduction premise of the doc? Or should I proceed with all the code snippets for those discussed possible cases?
