### ISSUE TITLE
Talawa-Docs update for API pushes is failing

### ISSUE THREAD

**Issue by palisadoes** [PalisadoesFoundation/talawa-docs#634]
Example:

1. This push action https://github.com/PalisadoesFoundation/talawa-api/actions/runs/4689169073/jobs/8310580892
1. Created by merging this PR: https://github.com/PalisadoesFoundation/talawa-api/pull/1295
1. Created this error in Talawa-Docs: https://github.com/PalisadoesFoundation/talawa-docs/actions/runs/4691260612

Why is that?

**Comment by palisadoes** [comment]
@EshaanAgg you'll need to work on this. Reference in API:

- https://github.com/PalisadoesFoundation/talawa-api/issues/1298

**Comment by EshaanAgg** [comment]
Got it.

**Comment by EshaanAgg** [comment]
@palisadoes The GitHub action is failing due to the inconsistent naming of files present in the `docs/talawa-api` directory. All the files for deployment to GitHub pages must be named in lowercase, and separated by `-` to avoid the deployment error we are facing now. 

Since the automatic push action from `Talawa API` only pushes to the `docs/github-actions/schema.json`, I don't think so that action is the reason for the failure of this job. Can you please let me know what is the function of the `docs/talawa-api` folder and maybe also tag the relevant contributor who worked on the same?

**Comment by EshaanAgg** [comment]
This might also be due to the `static/talawa` directory as the same too does not follow the proper naming convention. You can verify the same yourself from this error log:
```
Error:  Error: Prevent writing to file that only differs in casing or query string from already written file.
This will lead to a race-condition and corrupted files on case-insensitive file systems.
/home/runner/work/talawa-docs/talawa-docs/build/talawa/talawa/views_after_auth_screens_chat_widgets_chat_message_bubble/Message/message.html
/home/runner/work/talawa-docs/talawa-docs/build/talawa/talawa/views_after_auth_screens_chat_widgets_chat_message_bubble/Message/Message.html
    at checkSimilarFile (/home/runner/work/talawa-docs/talawa-docs/node_modules/webpack/lib/Compiler.js:666:11)
    at writeOut (/home/runner/work/talawa-docs/talawa-docs/node_modules/webpack/lib/Compiler.js:848:11)
    at /home/runner/work/talawa-docs/talawa-docs/node_modules/webpack/lib/util/fs.js:2[42](https://github.com/PalisadoesFoundation/talawa-docs/actions/runs/4691260612/jobs/8315484473#step:5:43):5
    at FSReqCallback.oncomplete (node:fs:198:23)
```
in [this job](https://github.com/PalisadoesFoundation/talawa-docs/actions/runs/4680880922/jobs/8292786777). 

@literalEval What do you think?

**Comment by literalEval** [comment]
@EshaanAgg that's exactly the issue and we have discussed this [here](https://github.com/PalisadoesFoundation/talawa/pull/1775#issuecomment-1506349737). A temporary solution can be to delete the conflicting files for now and let the deployment run, OR, we can change the attribute name in `Talawa` codebase which is causing this issue to something else, so that the files with conflicting names are never generated (something like the `message` attribute of the `Message` class can be renamed to `messageStr` maybe ?). 
But both of these are just temporary solutions, and we will need to either configure `Docusaurus` to accept such kind of files, or configure `Dart Doc` to generate different set of names (this seems highly unlikely to me though).

@EshaanAgg I am looking into `Dart Doc`. You may look into `Docusaurus`.

**Comment by EshaanAgg** [comment]
Got it @literalEval. I'll try to read about it too in greater detail. Thanks for the confirmation.

**Comment by literalEval** [comment]
@palisadoes I have opened an issue regarding this on the `Dart Doc`'s GitHub repo. You can have a look at it [here](https://github.com/dart-lang/dartdoc/issues/3388)
